version: '3'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
     - 5432:5432
    restart: always
  pgadmin:
    depends_on:
      - db
    image: thajeztah/pgadmin4
    ports:
     - 5050:5050
    restart: always

