version: '3.5'
services:
  client:
    hostname: grpc-client
    container_name: grpc-client
    build: ./client
    depends_on:
      - mserver
    ports:
      - 9002:9002
    networks:
      - tiered
  mserver:
    hostname: grpc-server
    container_name: grpc-server
    build: ./m
    ports:
      - 9001:9001
    networks:
      - tiered
networks:
  tiered: